import React from 'react'
import './Home_SafeMars.css'
import ReactWhatsapp from 'react-whatsapp';


export default function Home_SafeMars() {
    return (
        <div>
            <div className="swiper_slide_safeMars" >
                <div className="sec-overlay"></div>
                <div className="container">
                    <div className="left-holder slider-content">

                        <div className="row">
                            <div className="col-xs-12 col-md-12 text-center">
                                <div className="bnr-box">
                                    <span className="animated fadeInDown"><h1>SafeMars Clone </h1></span>
                                    <p className="animated fadeInDown">Develop Your Own SafeMars Platform By Availing Of Our SafeMars Clone Development Services. </p>
                                    <div className="animated fadeInUp mt-30">
                                        <a href="#contact" className="button-md dark-button two-btn js-scroll-trigger">Talk to Our Experts</a>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>






            <div className="section-block-grey">
                <div className="container">
                    <div className="row">
                        <div className="section-heading text-center">
                            <h2>SafeMars Clone Development Company </h2></div>
                        <div className="section-heading-line"></div>
                    </div>
                    <div className="row">
                        <div className="col-xs-12 col-sm-12 col-md-12 text-center">
                            <div className="pr-30-md">


                                <div className="mt-20">
                                    <p className="sec-txt">Our SafeMars Clone development company is one of the most proficient development companies in the crypto market. We have prior experience in developing crypto Clones for our clients. The SafeMoon token has taken over the crypto world after its arrival. The profit yields generated by this token was incredible. It was regarded as the next big thing, but it also had few issues like all the crypto projects. In order to rectify those issues, the SafeMars development protocol was introduced. At Better Logics, we are always updated with the current issues of the crypto market, and provide development services accordingly. We have the expertise to develop a SafeMars clone platform that functions similarly to the SafeMars protocol. To avail of our SafeMars clone development services, reach us soon!</p>

                                </div>
                                <div className="mt-30">
                                    <ReactWhatsapp number="+923330689368" message="Hi! I'm interested in one of your products at  Better Logics" className="whatsaapherebg   mt-4" >

                                        <a target="_blank" href="#" className="button-md dark-button two-btn">Connect With Whatsapp</a>

                                    </ReactWhatsapp>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>







            <div className="section-block guaranteed-sec">
                <div className="container">

                    <div className="guaranteed-box mt-50">
                        <div className="row">
                            <div className="col-lg-6 col-md-12 col-xs-12 col-sm-12 mt-5">
                                <div className="contentBox">
                                    <div className="section-heading left_tti">
                                        <h2>What is SafeMars? </h2>
                                        <div className="section-heading-line"></div>
                                    </div>
                                    <p className="mt-30 text-left p_Safe_Mood">SafeMars is an independent liquidity generating protocol.  The working of the SafeMars protocol depends on the tax reduction from the transaction fees. It deducts 4% as tax from the transaction fee, in which 2% is directly sent to the token holders and the other 2% is added to an automated liquidity pool. SafeMars exists within a unique domain of tokens, where the investors are rewarded with profits by just holding the token in the digital wallet. These rewards are entirely based on the success rate of the transactions that take place.  </p>
                                    <div className="animated banner_btn fadeInUp mt-30">
                                        <a href="#contact" className="button-md dark-button two-btn js-scroll-trigger">Talk to Our Experts</a>
                                    </div>
                                </div>
                            </div>
                            <div className="col-lg-6 col-md-12 col-xs-12 col-sm-12 text-center mt-5">
                                <div itemscope="" itemtype="https://schema.org/ImageObject" />
                                <meta itemprop="name" content=" Better Logics" />
                                <img data-src="what-is-safemars.jpg" width="100%" className="img-responsive" alt="SafeMars Clone" itemprop="contentUrl" src="what-is-safemars.jpg" width="100%" />
                                <meta itemprop="description" content="SafeMars Clone is an independent liquidity generating protocol. Get in touch with  Better Logics to know more about SafeMars Clone." />
                            </div>

                        </div>
                    </div>
                </div>

            </div>



            <div className="section-block-grey">
                <div className="container">
                    <div className="row">
                        <div className="section-heading text-center">
                            <h2>How Does a SafeMars Clone Work? </h2></div>
                        <div className="section-heading-line"></div>
                    </div>
                    <div className="row">
                        <div className="col-xs-12 col-sm-12 col-md-12 text-center">
                            <div className="pr-30-md">


                                <div className="mt-20">
                                    <p className="sec-txt">SafeMars clone is the complete replication of the SafeMars protocol. The functioning of this clone platform is very similar to the original SafeMars platform. The SafeMars clone is similar to the original, it provides high yielding and liquidity to the crypto tokens that are built on the Binance Smart Chain platform. The primary working of the SafeMars clone is dependent on their smart contracts. These SafeMars clone smart contracts implement a certain level of funds, represented as processing fees. This processing fee can be represented as the transaction fees that are deducted during the selling and buying process. Due to this implementation, the token holders receive passive revenues. This working method is said to reduce the possibilities of monetary losses due to token holding.</p>

                                </div>
                                <div className="mt-30">
                                    <ReactWhatsapp number="+923330689368" message="Hi! I'm interested in one of your products at  Better Logics" className="whatsaapherebg   mt-4" >

                                        <a target="_blank" href="#" className="button-md dark-button two-btn">Connect With Whatsapp</a>

                                    </ReactWhatsapp>

                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>






            <div className="section-block-grey explore-realm">
                <div className="container">
                    <div className="section-heading text-center">
                        <h3>How to build a Fundraising Platform like SafeMars</h3>
                        <div className="section-heading-line"></div>
                        <p className="text-center">At Better Logics, we have the technical expertise and knowledge to develop a fundraising platform like SafeMars. In the past, we have developed many fundraising platforms for our clients and it has been a great success in the crypto market. We specialize in developing a fundraising platform like SafeMars using two primary methods, such as whitelabel SafeMars token Clone and SafeMars Clone development platform.</p>
                    </div>
                    <div className="row">


                        <div className="col-xs-12 col-sm-12 col-md-12">



                        </div>
                        <div className="col-xs-12 col-sm-12 col-md-6 mt-5">
                            <div className="bx">
                                <p><strong>Whitelabel SafeMars Clone.</strong></p>
                                <p>In this method, the fundraising platform like SafeMars Clone is developed by implementing the whitelabel Clone solutions. This platform is customized based on the customer’s requirements and specifications at a minor level. It is a market-ready fundraising platform, thus, it can be deployed into the digital market in a very less time. The only drawback in implementing a whitelabel clone solution is that after the deployment, further customizations cannot be added on.</p>
                            </div>
                        </div>

                        <div className="col-xs-12 col-sm-12 col-md-6 mt-5">
                            <div className="bx">
                                <p><strong>SafeMars Clone Development Platform</strong></p>
                                <p>In this development method, the fundraising platform like SafeMars is developed by implementing the SafeMars Clone development solutions. The SafeMars Clone is the direct replica of the original platform in terms of the programming lines. It possesses all the core functionalities of the original platform. The SafeMars Clone is developed from scratch by implementing the features provided by the customers. This type of fundraising development platform can be deployed into the digital market similar to the whitelabel clone solutions, but with the only exception that further customization can be added on later.</p>
                            </div>
                        </div>


                    </div>


                </div>

            </div>

        </div>
    )
}
